FROM python:3.12.3

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN apt-get install apache2
# update pip globally within the container
RUN python3 -m pip install --upgrade pip
# download dependencies to the image and container
RUN python3 -m pip install -r requirements.txt

CMD [ "python", "manage.py", "runserver"]